package typwyliczeniowy;

public enum Wojewodztwa {
    DOLNYSLASK, KUJAWSKO_POMORSKIE, LODZKIE, LUBELSKIE, LUBUSKIE, MALOPOLSKIE, MAZOWIECKIE, OPOLSKIE, PODKARPACIE, PODLASKIE, POMORSKIE, SLASKIE, SWIETOKRZYSKIE, WARMINSKO_MAZURSKIE, WIELKOPOLSKIE, ZACHODNIO_POMORKSIE

}
